import { MarketplaceItemProps } from "./MarketplaceItem";

export const Collections: MarketplaceItemProps[] = [
  {
    title: "JUNO PUNKS",
    imageUrl: "/backgrounds/juno_punks.png",
    linkUrl: "/collections/junopunks",
    description:
      "Unique collectible PFP characters exclusively for the $JUNO community living on the #Cosmos | Free mint!",
  },
  {
    title: "Hope Galaxy NFT - Collection 1",
    imageUrl: "/backgrounds/Mintpass.png",
    linkUrl: "/collections/hopegalaxy1",
    description:
      "HOPE GALAXY NFT holders will be able to access the HopeGalaxy dapp which will enable them to stake their NFT and receive monthly passive income generated by NFT trades which are paid out once a month.",
  },
  {
    title: "Hope Galaxy Mint Pass 1",
    imageUrl: "/backgrounds/Collection.png",
    linkUrl: "/collections/mintpass1",
    description:
      "This mint pass is the ticket for the minting of the Hope Galaxy NFT collection once it is launched",
  },
];
