export interface MarketplaceBasicInfo {
  imageUrl: string;
  title: string;
  linkUrl: string;
  description: string;
}

export interface MarketplaceMintInfo {
  totalNfts: number;
  royalties: string;
  price: string;
  mintImage: string;
  mintDate?: string;
}

export interface MarketplaceInfo extends MarketplaceBasicInfo {
  mintInfo?: MarketplaceMintInfo;
}

const Collections: MarketplaceInfo[] = [
  {
    title: "Juno Punks NFT",
    imageUrl: "/backgrounds/juno_punks.png",
    linkUrl: "/collections/junopunks",
    description:
      "Unique collectible PFP characters exclusively for the $JUNO community living on the #Cosmos | Free mint!",
    mintInfo: {
      totalNfts: 500,
      royalties: "7% + 3%",
      price: "FREE MINT • Max 1 x wallet",
      mintImage: "/mint-images/JunoPunks.gif",
    },
  },
  {
    title: "Juno Farming",
    imageUrl: "/backgrounds/juno_farming.png",
    linkUrl: "/collections/junofarming",
    description:
      "The first NFT collection on JUNO blockchain, who rewards the NFT stakers. This project will rewards 50% you on every MINT and ALL TRANSACTION from every SINGLE NFT.",
    mintInfo: {
      totalNfts: 2500,
      royalties: "50% + 3%",
      price: "8 JUNO",
      mintImage: "/mint-images/JunoFarming.png",
    },
  },
  {
    title: "Neta NOTs",
    imageUrl: "/backgrounds/neta_nots.png",
    linkUrl: "/collections/netanots",
    description: "NetaNOTs are Space Warriors in the NOTs Universe",
    mintInfo: {
      totalNfts: 1950,
      royalties: "~% + 3%",
      price: "5 JUNO",
      mintImage: "/mint-images/NetaNOTs.png",
      mintDate: "20 June 2022",
    },
  },
  {
    title: "Hope Galaxy NFT - Collection 1",
    imageUrl: "/backgrounds/Mintpass.png",
    linkUrl: "/collections/hopegalaxy1",
    description:
      "HOPE GALAXY NFT holders will be able to access the HopeGalaxy dapp which will enable them to stake their NFT and receive monthly passive income generated by NFT trades which are paid out once a month.",
  },
  {
    title: "Hope Galaxy Mint Pass 1",
    imageUrl: "/backgrounds/Collection.png",
    linkUrl: "/collections/mintpass1",
    description:
      "This mint pass is the ticket for the minting of the Hope Galaxy NFT collection once it is launched",
  },
];

export default Collections;
